"""empty message

Revision ID: 21fb2358dd54
Revises: f62fe5cfe1ae
Create Date: 2023-08-30 12:52:46.795611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fb2358dd54'
down_revision = 'f62fe5cfe1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groomer_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.String(length=3000), nullable=False),
    sa.Column('rate', sa.Enum('1', '2', '3', '4', '5', name='rate_groomer'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('groomer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groomer_id'], ['groomer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groomer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groomer', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.drop_table('groomer_review')
    # ### end Alembic commands ###
