"""empty message

Revision ID: 36573e6fd1a5
Revises: 0516f96392a2
Create Date: 2023-08-30 08:49:13.561748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36573e6fd1a5'
down_revision = '0516f96392a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
