"""empty message

Revision ID: 4265aa214e0f
Revises: 3c3c49bb81bb
Create Date: 2023-08-29 17:17:55.483639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4265aa214e0f'
down_revision = '3c3c49bb81bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    with op.batch_alter_table('vet_favorite', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vet_favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['vet.id'], name='favorites_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    # ### end Alembic commands ###
