"""empty message

Revision ID: 53ab93275171
Revises: f85fd2f5db4e
Create Date: 2023-08-30 11:23:02.435224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ab93275171'
down_revision = 'f85fd2f5db4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groomer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('phone_number', sa.String(length=300), nullable=False),
    sa.Column('services', sa.String(length=1000), nullable=False),
    sa.Column('price_low', sa.Integer(), nullable=False),
    sa.Column('price_high', sa.Integer(), nullable=True),
    sa.Column('call_in', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groomer')
    # ### end Alembic commands ###
