"""empty message

Revision ID: 5d41a08a6abc
Revises: 06a7a15da2b3
Create Date: 2023-09-02 12:27:38.210823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d41a08a6abc'
down_revision = '06a7a15da2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groomer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('last_name', sa.String(length=70), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('average_rate', sa.String(length=10), nullable=True),
    sa.Column('services', sa.String(length=100), nullable=False),
    sa.Column('price_low', sa.Integer(), nullable=False),
    sa.Column('price_high', sa.Integer(), nullable=True),
    sa.Column('call_in', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('email')
    )
    op.create_table('groomerfavorites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('groomer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groomer_id'], ['groomer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groomerreviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('body', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rate', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('groomer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groomer_id'], ['groomer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groomerreviews')
    op.drop_table('groomerfavorites')
    op.drop_table('groomer')
    # ### end Alembic commands ###
