"""empty message

Revision ID: 8c492d2d5d52
Revises: 8aa792ac957c
Create Date: 2023-08-30 19:47:18.171714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c492d2d5d52'
down_revision = '8aa792ac957c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_walkers')
    op.drop_table('review_walkers')
    op.drop_table('walker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walker',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('walker_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('price_low', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_high', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='walker_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('review_walkers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('body', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('walker_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='review_walkers_user_id_fkey'),
    sa.ForeignKeyConstraint(['walker_id'], ['walker.id'], name='review_walkers_walker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='review_walkers_pkey')
    )
    op.create_table('favorite_walkers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('walker_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_walkers_user_id_fkey'),
    sa.ForeignKeyConstraint(['walker_id'], ['walker.id'], name='favorite_walkers_walker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_walkers_pkey')
    )
    # ### end Alembic commands ###
