"""empty message

Revision ID: 8e760e304c82
Revises: b58da7d6a0b3
Create Date: 2023-09-22 09:22:38.905254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e760e304c82'
down_revision = 'b58da7d6a0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_walkers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('groomer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('groomerfavorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('groomerreviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('pet_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=3000),
               type_=sa.String(length=10000),
               existing_nullable=False)

    with op.batch_alter_table('review_walkers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vet_favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vet_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('vet_review', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('vet_favorite', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('vet', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('review_walkers', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('pet_model', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('groomerreviews', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('groomerfavorites', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('groomer', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('favorite_walkers', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
