"""empty message

Revision ID: 96cf19ef31f7
Revises: b7e442254db1
Create Date: 2023-08-30 13:10:55.645613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96cf19ef31f7'
down_revision = 'b7e442254db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groomerfavorites')
    op.drop_table('groomer_review')
    op.drop_table('groomer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groomer',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('groomer_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('services', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('price_low', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_high', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('call_in', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('avatar', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='groomer_pkey'),
    sa.UniqueConstraint('company_name', name='groomer_company_name_key'),
    sa.UniqueConstraint('email', name='groomer_email_key'),
    sa.UniqueConstraint('phone_number', name='groomer_phone_number_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('groomer_review',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('body', sa.VARCHAR(length=3000), autoincrement=False, nullable=False),
    sa.Column('rate', postgresql.ENUM('1', '2', '3', '4', '5', name='rate_groomer'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('groomer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['groomer_id'], ['groomer.id'], name='groomer_review_groomer_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='groomer_review_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='groomer_review_pkey')
    )
    op.create_table('groomerfavorites',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('groomer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['groomer_id'], ['groomer.id'], name='groomerfavorites_groomer_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='groomerfavorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='groomerfavorites_pkey')
    )
    # ### end Alembic commands ###
