"""empty message

Revision ID: ab37ab13a18c
Revises: 96cf19ef31f7
Create Date: 2023-08-30 18:50:36.981018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab37ab13a18c'
down_revision = '96cf19ef31f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('street', sa.String(length=400), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
