"""empty message

Revision ID: adf89bf51020
Revises: 28ba3da08177
Create Date: 2023-09-07 17:30:28.162919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf89bf51020'
down_revision = '28ba3da08177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groomer', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=2000),
               nullable=True)
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('services',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2000),
               nullable=True)
        batch_op.alter_column('call_in',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_constraint('groomer_company_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['phone_number'])
        batch_op.drop_column('average_rate')

    with op.batch_alter_table('vet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_in', sa.Boolean(), nullable=True))

    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('services', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('call_in', sa.Boolean(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['phone_number'])
        batch_op.drop_column('surname')
        batch_op.drop_column('average_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rate', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('surname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('call_in')
        batch_op.drop_column('created_at')
        batch_op.drop_column('services')
        batch_op.drop_column('avatar')
        batch_op.drop_column('company_name')
        batch_op.drop_column('last_name')

    with op.batch_alter_table('vet', schema=None) as batch_op:
        batch_op.drop_column('call_in')

    with op.batch_alter_table('groomer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rate', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('groomer_company_name_key', ['company_name'])
        batch_op.alter_column('call_in',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('services',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('avatar',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
