"""empty message

Revision ID: b7e442254db1
Revises: bcafa9e87534
Create Date: 2023-08-30 13:01:22.567825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e442254db1'
down_revision = 'bcafa9e87534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groomerfavorites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('groomer_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['groomer_id'], ['groomer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groomerfavorites')
    # ### end Alembic commands ###
