"""empty message

Revision ID: c5e8fa0d3bfd
Revises: 33d11e743b4e
Create Date: 2023-09-07 10:34:50.614346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e8fa0d3bfd'
down_revision = '33d11e743b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_model',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('animal_type', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groomer', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('vet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vet', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
        batch_op.drop_column('address')

    with op.batch_alter_table('groomer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    op.drop_table('pet_model')
    # ### end Alembic commands ###
