"""empty message

Revision ID: cd29081f926b
Revises: 8c1d437e63be
Create Date: 2023-09-07 16:46:29.474678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd29081f926b'
down_revision = '8c1d437e63be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groomer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=False))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('vet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=False))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=False))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('zip_code')

    with op.batch_alter_table('vet', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_column('zip_code')

    with op.batch_alter_table('groomer', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
