"""empty message

Revision ID: e9166db92fe8
Revises: cd29081f926b
Create Date: 2023-09-07 16:48:16.782260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9166db92fe8'
down_revision = 'cd29081f926b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groomer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               nullable=True)

    with op.batch_alter_table('vet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=True))

    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('zip_code')

    with op.batch_alter_table('vet', schema=None) as batch_op:
        batch_op.drop_column('zip_code')

    with op.batch_alter_table('groomer', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
