"""empty message

Revision ID: f62fe5cfe1ae
Revises: 53ab93275171
Create Date: 2023-08-30 12:29:59.962029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62fe5cfe1ae'
down_revision = '53ab93275171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groomer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groomer', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
